server:
  port: 8081
---
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: register-device
        uri: http://localhost:8000
        predicates:
          - Path=/register-device/**
        filters:
          - StripPrefix=1
      - id: register-data
        uri: http://localhost:8001
        predicates:
          - Path=/register-data/**
        filters:
          - StripPrefix=1
      - id: users
        uri: http://localhost:8080
        predicates:
          - Path=/users/**
        filters:
          - StripPrefix=1